# Generated by Django 2.0.1 on 2018-01-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='article',
            new_name='post',
        ),
    ]
